version: '3.3'

services:
  sys0-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: sys0-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      sys0-network:
        ipv4_address: 192.168.178.2
    volumes:
      - sys0-db:/var/lib/mysql
    restart: always

  sys0-srv:
    build:
      context: .
      dockerfile: srv_dockerfile
    container_name: sys0-srv
    networks:
      sys0-network:
        ipv4_address: 192.168.178.3
    ports:
      - "80:80"
    depends_on:
      - sys0-db
    volumes:
      - ./sys0-code:/var/www/html
      - ./apache-conf:/etc/apache2/sites-enabled/
      - ./php-conf:/usr/local/etc/php/
    restart: always
networks:
  sys0-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.178.0/24

volumes:
   sys0-db:
    external: true
